# Generated by Django 6.1 on 2026-08-31 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("expenses", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="expense",
            options={"ordering": ["created_at"]},
        ),
        migrations.AlterModelOptions(
            name="group",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AlterModelOptions(
            name="settlement",
            options={"ordering": ["created_at"]},
        ),
    ]
